stages:
  - .pre
  - build
  - publish
  - deploy

include:
  - local: 'workflow.gitlab-ci.yml'
  - local: 'docker.gitlab-ci.yml'
  - local: 'docker-auth.yml'
  - local: 'gitversion-ci-cd-plugin-extension.gitlab-ci.yml'
  - local: 'prepare-settings.yml'
  - local: 'release.gitlab-ci.yml'
  - local: '.ci/build.gitlab-ci.yml'
  - local: '.ci/deploy.gitlab-ci.yml'

variables:
  DOCKER_TAG:
    value: main
    description: Docker image tag used for build and deploy
  DEPLOY_ENVIRONMENT:
    value: development
    description: Target environment (development or production)
