# Generated by Django 6.0.5 on 2026-05-25 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('number', models.CharField(max_length=32, unique=True)),
                ('store_class', models.CharField(choices=[('ECONOMY', 'Эконом'), ('STANDARD', 'Стандарт'), ('PREMIUM', 'Премиум')], default='STANDARD', max_length=16)),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
            },
        ),
        migrations.CreateModel(
            name='SupplierBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('city', models.CharField(max_length=80)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('contact_phone', models.CharField(blank=True, max_length=32)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name': 'Торговая база',
                'verbose_name_plural': 'Торговые базы',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('is_open', models.BooleanField(default=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='shop.store')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('CONFIRMED', 'Подтвержден'), ('RECEIVED', 'Получен'), ('CANCELLED', 'Отменен')], default='DRAFT', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='shop.department')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='shop.store')),
                ('supplier_base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='shop.supplierbase')),
            ],
            options={
                'verbose_name': 'Закупка',
                'verbose_name_plural': 'Закупки',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='shop.department')),
                ('sold_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='shop.store')),
            ],
            options={
                'verbose_name': 'Продажа',
                'verbose_name_plural': 'Продажи',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('unit', models.CharField(choices=[('PCS', 'шт'), ('KG', 'кг'), ('L', 'л'), ('PACK', 'упак')], default='PCS', max_length=8)),
                ('description', models.TextField(blank=True)),
                ('preferred_base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_products', to='shop.supplierbase')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='BaseStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=80)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_stocks', to='shop.product')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='shop.supplierbase')),
            ],
            options={
                'verbose_name': 'Остаток на базе',
                'verbose_name_plural': 'Остатки на базах',
            },
        ),
        migrations.CreateModel(
            name='DepartmentStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=80)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='shop.department')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_stocks', to='shop.product')),
            ],
            options={
                'verbose_name': 'Остаток в отделе',
                'verbose_name_plural': 'Остатки в отделах',
                'constraints': [models.UniqueConstraint(fields=('department', 'product', 'grade'), name='uniq_department_product_grade'), models.CheckConstraint(condition=models.Q(('retail_price__gt', 0)), name='retail_price_gt_0')],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=80)),
                ('quantity', models.PositiveIntegerField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.purchaseorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='shop.product')),
            ],
            options={
                'verbose_name': 'Позиция закупки',
                'verbose_name_plural': 'Позиции закупки',
                'constraints': [models.UniqueConstraint(fields=('order', 'product', 'grade'), name='uniq_order_product_grade'), models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='purchase_item_qty_gt_0'), models.CheckConstraint(condition=models.Q(('purchase_price__gt', 0)), name='purchase_item_price_gt_0')],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=80)),
                ('quantity', models.PositiveIntegerField()),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='shop.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.sale')),
            ],
            options={
                'verbose_name': 'Позиция продажи',
                'verbose_name_plural': 'Позиции продажи',
                'constraints': [models.UniqueConstraint(fields=('sale', 'product', 'grade'), name='uniq_sale_product_grade'), models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='sale_item_qty_gt_0'), models.CheckConstraint(condition=models.Q(('retail_price__gt', 0)), name='sale_item_price_gt_0')],
            },
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('store', 'name'), name='uniq_department_store_name'),
        ),
        migrations.AddConstraint(
            model_name='basestock',
            constraint=models.UniqueConstraint(fields=('base', 'product', 'grade'), name='uniq_base_product_grade'),
        ),
        migrations.AddConstraint(
            model_name='basestock',
            constraint=models.CheckConstraint(condition=models.Q(('purchase_price__gt', 0)), name='base_purchase_price_gt_0'),
        ),
    ]
