build_backend:
  extends: .docker
  stage: build_backend
  cache:
    paths:
      - .cache/pip
  script:
    - !reference [.docker_login, before_script]
    - docker build -f backend/Dockerfile -t "$CI_REGISTRY_IMAGE/backend:$DOCKER_TAG" .
    - docker push "$CI_REGISTRY_IMAGE/backend:$DOCKER_TAG"
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+(\.\d+)?$/

build_frontend:
  extends: .docker
  stage: build_frontend
  cache:
    paths:
      - .cache/pip
  script:
    - !reference [.docker_login, before_script]
    - docker build -f frontend/Dockerfile --target prod -t "$CI_REGISTRY_IMAGE/frontend:$DOCKER_TAG" .
    - docker push "$CI_REGISTRY_IMAGE/frontend:$DOCKER_TAG"
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+(\.\d+)?$/
